name: Build and Deploy
on: 
  push:
    paths: [".storybook/**", "src/**"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: npm Install
        run: npm install
      - name: npm Build
        run:  npm run build:storybook
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: static # The folder that we serve our Storybook files from
